source "https://rubygems.org"

gem 'sinatra', '~> 2.1'

gem 'sinatra-activerecord'

gem 'activerecord', '~> 6.1'

gem 'rack-contrib'

# More Rack middleware! Used to handle CORS requests
# https://github.com/cyu/rack-cors
gem "rack-cors", "~> 1.1"

gem 'faker'

gem 'sqlite3', '~> 1.4'

gem 'rake'

gem 'require_all'

gem 'webrick'

gem 'json'

gem 'pry'

gem 'date'

gem 'rerun'